services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    tty: true
    volumes:
      - .:/workspace
      # - rust-target:/workspace/target

# volumes:
#   rust-target: